import image from '../assets/categorias/porDefecto.png';

export const parentCategories = [
  { id: 88, name: 'Indumentaria' },
  { id: 130, name: 'Blanquería' },
  { id: 131, name: 'Bisutería' },
];

export const indumentariaCategories = [
  {
    gender: { id: 3, name: 'Mujer' },
    categories: [
      { id: 91, name: 'Blusas', image },
      { id: 120, name: 'Bolsos', image },
      { id: 105, name: 'Body', image },
      { id: 115, name: 'Bufandas', image },
      { id: 106, name: 'Buzos', image },
      { id: 90, name: 'Calzas', image },
      { id: 102, name: 'Calzado', image },
      { id: 107, name: 'Camperas', image },
      { id: 92, name: 'Camisas', image },
      { id: 99, name: 'Chombas', image },
      { id: 118, name: 'Cinturones', image },
      { id: 111, name: 'Conjuntos', image },
      { id: 109, name: 'Enteritos', image },
      { id: 96, name: 'Falsas', image },
      { id: 123, name: 'Gafas de sol', image },
      { id: 114, name: 'Gorros', image },
      { id: 117, name: 'Guantes', image },
      { id: 89, name: 'Jeans', image },
      { id: 103, name: 'Lencería', image },
      { id: 113, name: 'Monitos', image },
      { id: 121, name: 'Mochilas', image },
      { id: 98, name: 'Musculosas', image },
      { id: 124, name: 'Otros', image },
      { id: 94, name: 'Pantalones', image },
      { id: 125, name: 'Pantalones y calzas', image },
      { id: 122, name: 'Paraguas', image },
      { id: 110, name: 'Pijamas', image },
      { id: 116, name: 'Ropa itnerior', image },
      { id: 97, name: 'Remeras', image },
      { id: 93, name: 'Sweaters', image },
      { id: 127, name: 'Calzados', image },
      { id: 95, name: 'Shorts', image },
      { id: 126, name: 'Shorts y polleras', image },
      { id: 100, name: 'Tops', image },
      { id: 101, name: 'Vestidos', image },
      { id: 104, name: 'Zapatillas', image },
    ]
  },
  {
    gender: { id: 2, name: 'Hombre' },
    categories: [
      { id: 120, name: 'Bolsos', image },
      { id: 115, name: 'Bufandas', image },
      { id: 106, name: 'Buzos', image },
      { id: 102, name: 'Calzado', image },
      { id: 107, name: 'Camperas', image },
      { id: 92, name: 'Camisas', image },
      { id: 99, name: 'Chombas', image },
      { id: 118, name: 'Cinturones', image },
      { id: 111, name: 'Conjuntos', image },
      { id: 123, name: 'Gafas de sol', image },
      { id: 114, name: 'Gorros', image },
      { id: 117, name: 'Guantes', image },
      { id: 89, name: 'Jeans', image },
      { id: 121, name: 'Mochilas', image },
      { id: 98, name: 'Musculosas', image },
      { id: 124, name: 'Otros', image },
      { id: 94, name: 'Pantalones', image },
      { id: 125, name: 'Pantalones y calzas', image },
      { id: 122, name: 'Paraguas', image },
      { id: 110, name: 'Pijamas', image },
      { id: 116, name: 'Ropa itnerior', image },
      { id: 97, name: 'Remeras', image },
      { id: 93, name: 'Sweaters', image },
      { id: 127, name: 'Calzados', image },
      { id: 95, name: 'Shorts', image },
      { id: 104, name: 'Zapatillas', image },
    ]
  },
  {
    gender: { id: 5, name: 'Niña' },
    categories: [
      { id: 91, name: 'Blusas', image },
      { id: 120, name: 'Bolsos', image },
      { id: 105, name: 'Body', image },
      { id: 115, name: 'Bufandas', image },
      { id: 106, name: 'Buzos', image },
      { id: 90, name: 'Calzas', image },
      { id: 127, name: 'Calzados', image },
      { id: 102, name: 'Calzado', image },
      { id: 107, name: 'Camperas', image },
      { id: 92, name: 'Camisas', image },
      { id: 99, name: 'Chombas', image },
      { id: 118, name: 'Cinturones', image },
      { id: 111, name: 'Conjuntos', image },
      { id: 109, name: 'Enteritos', image },
      { id: 96, name: 'Falsas', image },
      { id: 114, name: 'Gorros', image },
      { id: 117, name: 'Guantes', image },
      { id: 89, name: 'Jeans', image },
      { id: 121, name: 'Mochilas', image },
      { id: 113, name: 'Monitos', image },
      { id: 98, name: 'Musculosas', image },
      { id: 124, name: 'Otros', image },
      { id: 94, name: 'Pantalones', image },
      { id: 125, name: 'Pantalones y calzas', image },
      { id: 122, name: 'Paraguas', image },
      { id: 110, name: 'Pijamas', image },
      { id: 116, name: 'Ropa itnerior', image },
      { id: 97, name: 'Remeras', image },
      { id: 93, name: 'Sweaters', image },
      { id: 95, name: 'Shorts', image },
      { id: 126, name: 'Shorts y polleras', image },
      { id: 100, name: 'Tops', image },
      { id: 101, name: 'Vestidos', image },
      { id: 104, name: 'Zapatillas', image },
    ]
  },
  {
    gender: { id: 4, name: 'Niño' },
    categories: [
      { id: 120, name: 'Bolsos', image },
      { id: 115, name: 'Bufandas', image },
      { id: 106, name: 'Buzos', image },
      { id: 127, name: 'Calzados', image },
      { id: 102, name: 'Calzado', image },
      { id: 107, name: 'Camperas', image },
      { id: 92, name: 'Camisas', image },
      { id: 99, name: 'Chombas', image },
      { id: 118, name: 'Cinturones', image },
      { id: 111, name: 'Conjuntos', image },
      { id: 114, name: 'Gorros', image },
      { id: 117, name: 'Guantes', image },
      { id: 89, name: 'Jeans', image },
      { id: 121, name: 'Mochilas', image },
      { id: 98, name: 'Musculosas', image },
      { id: 124, name: 'Otros', image },
      { id: 94, name: 'Pantalones', image },
      { id: 125, name: 'Pantalones y calzas', image },
      { id: 122, name: 'Paraguas', image },
      { id: 110, name: 'Pijamas', image },
      { id: 116, name: 'Ropa itnerior', image },
      { id: 97, name: 'Remeras', image },
      { id: 93, name: 'Sweaters', image },
      { id: 95, name: 'Shorts', image },
      { id: 104, name: 'Zapatillas', image },
    ]
  },
  {
    gender: { id: 6, name: 'Bebé' },
    categories: [
      { id: 112, name: 'Baberos', image },
      { id: 120, name: 'Bolsos', image },
      { id: 105, name: 'Body', image },
      { id: 115, name: 'Bufandas', image },
      { id: 106, name: 'Buzos', image },
      { id: 127, name: 'Calzados', image },
      { id: 102, name: 'Calzado', image },
      { id: 107, name: 'Camperas', image },
      { id: 111, name: 'Conjuntos', image },
      { id: 109, name: 'Enteritos', image },
      { id: 114, name: 'Gorros', image },
      { id: 117, name: 'Guantes', image },
      { id: 89, name: 'Jeans', image },
      { id: 121, name: 'Mochilas', image },
      { id: 113, name: 'Monitos', image },
      { id: 98, name: 'Musculosas', image },
      { id: 124, name: 'Otros', image },
      { id: 94, name: 'Pantalones', image },
      { id: 125, name: 'Pantalones y calzas', image },
      { id: 122, name: 'Paraguas', image },
      { id: 110, name: 'Pijamas', image },
      { id: 116, name: 'Ropa itnerior', image },
      { id: 97, name: 'Remeras', image },
      { id: 93, name: 'Sweaters', image },
      { id: 95, name: 'Shorts', image },
      { id: 104, name: 'Zapatillas', image },
      { id: 101, name: 'Vestidos', image },
    ]
  }
];

export const blanqueriaCategories = [
  {
    categories: [
      { id: 132, name: 'Sábanas', image },
      { id: 133, name: 'Toallas', image },
      { id: 134, name: 'Cortinas', image },
    ]
  }
];

export const bisuteriaCategories = [
  {
    categories: [
      { id: 135, name: 'Collares', image },
      { id: 136, name: 'Pulseras', image },
      { id: 137, name: 'Anillos', image },
    ]
  }
];