import image from '../assets/categorias/porDefecto.png';

export const parentCategories = [
  { id: 88, name: 'Indumentaria' },
  { id: 130, name: 'Blanquería' },
  { id: 131, name: 'Bisutería' },
];

export const genders = [
  { 
    id: 2, 
    name: 'Hombre', 
    url: 'hombre',
    categories: [
      { id: 1, name: 'Jeans', image },
      { id: 2, name: 'Pantalones', image },
      { id: 3, name: 'Bermudas y shorts', image },
      { id: 1, name: 'Camperas', image },
      { id: 2, name: 'Remeras', image },
      { id: 3, name: 'Camisas', image },
      { id: 1, name: 'Chombas', image },
      { id: 2, name: 'Buzos', image },
      { id: 3, name: 'Sweaters', image },
      { id: 1, name: 'Ropa interior', image },
      { id: 2, name: 'Calzados', image },
      { id: 3, name: 'Otros', image },
    ],
  },
  { 
    id: 3, 
    name: 'Mujer', 
    url: 'mujer',
    categories: [
      { id: 1, name: 'Jeans', image },
      { id: 2, name: 'Pantalones y calzas', image },
      { id: 3, name: 'Shorts y polleras', image },
      { id: 1, name: 'Camperas', image },
      { id: 2, name: 'Remeras', image },
      { id: 3, name: 'Camisas', image },
      { id: 1, name: 'Buzos', image },
      { id: 2, name: 'Sweaters', image },
      { id: 3, name: 'Vestidos', image },
      { id: 1, name: 'Lencería y mallas', image },
      { id: 2, name: 'Calzados', image },
      { id: 3, name: 'Otros', image },
    ],
  },
  { 
    id: 4, 
    name: 'Niño', 
    url: 'niño',
    categories: [
      { id: 1, name: 'Jeans', image },
      { id: 2, name: 'Pantalones', image },
      { id: 3, name: 'Bermudas y shorts', image },
      { id: 1, name: 'Camperas', image },
      { id: 2, name: 'Remeras', image },
      { id: 3, name: 'Camisas', image },
      { id: 1, name: 'Chombas', image },
      { id: 2, name: 'Buzos', image },
      { id: 3, name: 'Sweaters', image },
      { id: 1, name: 'Ropa interior', image },
      { id: 2, name: 'Calzados', image },
      { id: 3, name: 'Otros', image },
    ], 
  },
  { 
    id: 5, 
    name: 'Niña', 
    url: 'niña',
    categories: [
      { id: 1, name: ' Jeans', image },
      { id: 2, name: 'Pantalones y calzas', image },
      { id: 3, name: 'Shorts y polleras', image },
      { id: 1, name: 'Camperas', image },
      { id: 2, name: 'Remeras', image },
      { id: 3, name: 'Camisas', image },
      { id: 1, name: 'Buzos', image },
      { id: 2, name: 'Swaters', image },
      { id: 3, name: 'Vestidos', image },
      { id: 1, name: 'Ropa interior y mallas', image },
      { id: 2, name: 'Calzados', image },
      { id: 3, name: 'Otros', image },
    ],
  },
  { 
    id: 6, 
    name: 'Bebés', 
    url: 'bebes',
    categories: [
      { id: 1, name: 'Jeans', image },
      { id: 2, name: 'Pantalones y shorts', image },
      { id: 3, name: 'Camperas', image },
      { id: 1, name: 'Remeras', image },
      { id: 2, name: 'Camisas', image },
      { id: 3, name: 'Bodys', image },
      { id: 1, name: 'Buzos y swaters', image },
      { id: 2, name: 'Vestidos', image },
      { id: 3, name: 'Conjuntos y enteritos', image },
      { id: 2, name: 'Ropa interior y mallas', image },
      { id: 1, name: 'Calzados', image },
      { id: 3, name: 'Otros', image },
    ],
  },
  { 
    id: 7, 
    name: 'Más', 
    url: 'mas',
    categories: [
      { id: 2, name: 'Blanquería', image },
      { id: 3, name: 'Bisutería', image },
    ],
  },
];