export const parentCategories = [
  { id: 88, name: 'Indumentaria' },
  { id: 130, name: 'Blanquería' },
  { id: 131, name: 'Bisutería' },
];

export const indumentariaCategories = [
  {
    gender: { id: 3, name: 'Mujer' },
    categories: [
      { id: 91, name: 'Blusas' },
      { id: 120, name: 'Bolsos' },
      { id: 105, name: 'Body' },
      { id: 115, name: 'Bufandas' },
      { id: 106, name: 'Buzos' },
      { id: 90, name: 'Calzas' },
      { id: 102, name: 'Calzado' },
      { id: 107, name: 'Camperas' },
      { id: 92, name: 'Camisas' },
      { id: 99, name: 'Chombas' },
      { id: 118, name: 'Cinturones' },
      { id: 111, name: 'Conjuntos' },
      { id: 109, name: 'Enteritos' },
      { id: 96, name: 'Falsas' },
      { id: 123, name: 'Gafas de sol' },
      { id: 114, name: 'Gorros' },
      { id: 117, name: 'Guantes' },
      { id: 89, name: 'Jeans' },
      { id: 103, name: 'Lencería' },
      { id: 113, name: 'Monitos' },
      { id: 121, name: 'Mochilas' },
      { id: 98, name: 'Musculosas' },
      { id: 124, name: 'Otros' },
      { id: 94, name: 'Pantalones' },
      { id: 125, name: 'Pantalones y calzas' },
      { id: 122, name: 'Paraguas' },
      { id: 110, name: 'Pijamas' },
      { id: 116, name: 'Ropa itnerior' },
      { id: 97, name: 'Remeras' },
      { id: 93, name: 'Sweaters' },
      { id: 127, name: 'Calzados' },
      { id: 95, name: 'Shorts' },
      { id: 126, name: 'Shorts y polleras' },
      { id: 100, name: 'Tops' },
      { id: 101, name: 'Vestidos' },
      { id: 104, name: 'Zapatillas' },
    ]
  },
  {
    gender: { id: 2, name: 'Hombre' },
    categories: [
      { id: 120, name: 'Bolsos' },
      { id: 115, name: 'Bufandas' },
      { id: 106, name: 'Buzos' },
      { id: 102, name: 'Calzado' },
      { id: 107, name: 'Camperas' },
      { id: 92, name: 'Camisas' },
      { id: 99, name: 'Chombas' },
      { id: 118, name: 'Cinturones' },
      { id: 111, name: 'Conjuntos' },
      { id: 123, name: 'Gafas de sol' },
      { id: 114, name: 'Gorros' },
      { id: 117, name: 'Guantes' },
      { id: 89, name: 'Jeans' },
      { id: 121, name: 'Mochilas' },
      { id: 98, name: 'Musculosas' },
      { id: 124, name: 'Otros' },
      { id: 94, name: 'Pantalones' },
      { id: 125, name: 'Pantalones y calzas' },
      { id: 122, name: 'Paraguas' },
      { id: 110, name: 'Pijamas' },
      { id: 116, name: 'Ropa itnerior' },
      { id: 97, name: 'Remeras' },
      { id: 93, name: 'Sweaters' },
      { id: 127, name: 'Calzados' },
      { id: 95, name: 'Shorts' },
      { id: 104, name: 'Zapatillas' },
    ]
  },
  {
    gender: { id: 5, name: 'Niña' },
    categories: [
      { id: 91, name: 'Blusas' },
      { id: 120, name: 'Bolsos' },
      { id: 105, name: 'Body' },
      { id: 115, name: 'Bufandas' },
      { id: 106, name: 'Buzos' },
      { id: 90, name: 'Calzas' },
      { id: 127, name: 'Calzados' },
      { id: 102, name: 'Calzado' },
      { id: 107, name: 'Camperas' },
      { id: 92, name: 'Camisas' },
      { id: 99, name: 'Chombas' },
      { id: 118, name: 'Cinturones' },
      { id: 111, name: 'Conjuntos' },
      { id: 109, name: 'Enteritos' },
      { id: 96, name: 'Falsas' },
      { id: 114, name: 'Gorros' },
      { id: 117, name: 'Guantes' },
      { id: 89, name: 'Jeans' },
      { id: 121, name: 'Mochilas' },
      { id: 113, name: 'Monitos' },
      { id: 98, name: 'Musculosas' },
      { id: 124, name: 'Otros' },
      { id: 94, name: 'Pantalones' },
      { id: 125, name: 'Pantalones y calzas' },
      { id: 122, name: 'Paraguas' },
      { id: 110, name: 'Pijamas' },
      { id: 116, name: 'Ropa itnerior' },
      { id: 97, name: 'Remeras' },
      { id: 93, name: 'Sweaters' },
      { id: 95, name: 'Shorts' },
      { id: 126, name: 'Shorts y polleras' },
      { id: 100, name: 'Tops' },
      { id: 101, name: 'Vestidos' },
      { id: 104, name: 'Zapatillas' },
    ]
  },
  {
    gender: { id: 4, name: 'Niño' },
    categories: [
      { id: 120, name: 'Bolsos' },
      { id: 115, name: 'Bufandas' },
      { id: 106, name: 'Buzos' },
      { id: 127, name: 'Calzados' },
      { id: 102, name: 'Calzado' },
      { id: 107, name: 'Camperas' },
      { id: 92, name: 'Camisas' },
      { id: 99, name: 'Chombas' },
      { id: 118, name: 'Cinturones' },
      { id: 111, name: 'Conjuntos' },
      { id: 114, name: 'Gorros' },
      { id: 117, name: 'Guantes' },
      { id: 89, name: 'Jeans' },
      { id: 121, name: 'Mochilas' },
      { id: 98, name: 'Musculosas' },
      { id: 124, name: 'Otros' },
      { id: 94, name: 'Pantalones' },
      { id: 125, name: 'Pantalones y calzas' },
      { id: 122, name: 'Paraguas' },
      { id: 110, name: 'Pijamas' },
      { id: 116, name: 'Ropa itnerior' },
      { id: 97, name: 'Remeras' },
      { id: 93, name: 'Sweaters' },
      { id: 95, name: 'Shorts' },
      { id: 104, name: 'Zapatillas' },
    ]
  },
  {
    gender: { id: 6, name: 'Bebé' },
    categories: [
      { id: 112, name: 'Baberos' },
      { id: 120, name: 'Bolsos' },
      { id: 105, name: 'Body' },
      { id: 115, name: 'Bufandas' },
      { id: 106, name: 'Buzos' },
      { id: 127, name: 'Calzados' },
      { id: 102, name: 'Calzado' },
      { id: 107, name: 'Camperas' },
      { id: 111, name: 'Conjuntos' },
      { id: 109, name: 'Enteritos' },
      { id: 114, name: 'Gorros' },
      { id: 117, name: 'Guantes' },
      { id: 89, name: 'Jeans' },
      { id: 121, name: 'Mochilas' },
      { id: 113, name: 'Monitos' },
      { id: 98, name: 'Musculosas' },
      { id: 124, name: 'Otros' },
      { id: 94, name: 'Pantalones' },
      { id: 125, name: 'Pantalones y calzas' },
      { id: 122, name: 'Paraguas' },
      { id: 110, name: 'Pijamas' },
      { id: 116, name: 'Ropa itnerior' },
      { id: 97, name: 'Remeras' },
      { id: 93, name: 'Sweaters' },
      { id: 95, name: 'Shorts' },
      { id: 104, name: 'Zapatillas' },
      { id: 101, name: 'Vestidos' },
    ]
  }
];

export const blanqueriaCategories = [
  { id: 132, name: 'Sábanas' },
  { id: 133, name: 'Toallas' },
  { id: 134, name: 'Cortinas' },
];

export const bisuteriaCategories = [
  { id: 135, name: 'Collares' },
  { id: 136, name: 'Pulseras' },
  { id: 137, name: 'Anillos' },
];